cc_binary(
    name = "vtk_cylinder",
    srcs = ["vtk_cylinder.cpp"],
    deps = ["@vtk//:vtk","@eigen//:eigen"],
)

cc_binary(
    name = "vtk_triangle",
    srcs = ["vtk_triangle.cpp"],
    deps = ["@vtk//:vtk","@eigen//:eigen"],
)

cc_binary(
    name = "vtk_text",
    srcs = ["vtk_text.cpp"],
    deps = ["@vtk//:vtk","@eigen//:eigen"],
)
