#load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary")

# cc_binary(
#     name = "main",
#     srcs = glob(["**/*.cpp"]) + glob(["**/*.hpp"]) + glob(["**/*.h"]),
#     deps = ["@eigen//:eigen",
#             "//code_utilities:code_utilities",
#             "@sdl2//:sdl2"]
# )
