cc_binary(
  name = "introduction_ex3",
  srcs = ["src/introduction_ex3.exact_solution.C",
          "src/introduction_ex3.C"],
  deps = ["@libmesh//:libmesh"]
)

cc_binary(
  name = "vector_f1_ex1",
  srcs = ["src/vector_fe_ex1.exact_solution.C",
          "src/vector_fe_ex1.C"],
  deps = ["@libmesh//:libmesh"]
)

cc_binary(
  name = "element_properties",
  srcs = ["src/element_properties.cc"],
  deps = ["@libmesh//:libmesh",
          "//mathx_core:mathx_core"]
)
